INSERT INTO sys_email_configs (
    id,
    created_at,
    created_by,
    updated_at,
    updated_by,
    description,
    code,
    name,
    provider_type,
    host,
    port,
    username,
    password,
    from_address,
    from_name,
    reply_to,
    protocol,
    encoding,
    auth_enabled,
    starttls_enabled,
    ssl_enabled,
    debug_enabled,
    timeout_ms,
    connection_timeout_ms,
    write_timeout_ms,
    max_recipients,
    default_cc,
    default_bcc,
    provider_settings,
    config_json,
    enabled,
    is_default
)
VALUES (
    '00000000-0000-0000-0000-000000000011',
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM',
    'Default SMTP configuration loaded from database',
    'DEFAULT_SMTP',
    'Default Gmail SMTP',
    'SMTP',
    'smtp.gmail.com',
    587,
    'truongducbao290402@gmail.com',
    'CHANGE_ME_SMTP_PASSWORD',
    'truongducbao290402@gmail.com',
    'Ledger Service',
    'truongducbao290402@gmail.com',
    'smtp',
    'UTF-8',
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '{}'::jsonb,
    jsonb_build_object(
        'host', 'smtp.gmail.com',
        'port', 587,
        'username', 'truongducbao290402@gmail.com',
        'password', 'tfcr josj npro npsy',
        'fromAddress', 'truongducbao290402@gmail.com',
        'fromName', 'Ledger Service',
        'replyTo', 'truongducbao290402@gmail.com',
        'protocol', 'smtp',
        'encoding', 'UTF-8',
        'authEnabled', TRUE,
        'starttlsEnabled', TRUE,
        'sslEnabled', FALSE,
        'debugEnabled', FALSE,
        'timeoutMs', NULL,
        'connectionTimeoutMs', NULL,
        'writeTimeoutMs', NULL,
        'maxRecipients', NULL,
        'defaultCc', '[]'::jsonb,
        'defaultBcc', '[]'::jsonb,
        'providerSettings', '{}'::jsonb
    ),
    TRUE,
    TRUE
)
ON CONFLICT (code) DO UPDATE SET
    updated_at = EXCLUDED.updated_at,
    updated_by = EXCLUDED.updated_by,
    description = EXCLUDED.description,
    provider_type = EXCLUDED.provider_type,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    username = EXCLUDED.username,
    password = EXCLUDED.password,
    from_address = EXCLUDED.from_address,
    from_name = EXCLUDED.from_name,
    reply_to = EXCLUDED.reply_to,
    protocol = EXCLUDED.protocol,
    encoding = EXCLUDED.encoding,
    auth_enabled = EXCLUDED.auth_enabled,
    starttls_enabled = EXCLUDED.starttls_enabled,
    ssl_enabled = EXCLUDED.ssl_enabled,
    debug_enabled = EXCLUDED.debug_enabled,
    timeout_ms = EXCLUDED.timeout_ms,
    connection_timeout_ms = EXCLUDED.connection_timeout_ms,
    write_timeout_ms = EXCLUDED.write_timeout_ms,
    max_recipients = EXCLUDED.max_recipients,
    default_cc = EXCLUDED.default_cc,
    default_bcc = EXCLUDED.default_bcc,
    provider_settings = EXCLUDED.provider_settings,
    config_json = EXCLUDED.config_json,
    enabled = EXCLUDED.enabled,
    is_default = EXCLUDED.is_default;
